- Name: combinatorics
  Prefix: cpp
  Display: Combinatorics
  Description: Suite of efficient combinatoric utility functions.

- Name: bin_exp
  Prefix: cpp
  Display: Binary Exponentiation with Modulo
  Description: Effective computation of large exponents module a number.

- Name: ext_euclid_iter
  Prefix: cpp
  Display: Extended Euclidean Algorithm (Iterative)
  Description: Calculates the GCD of A and B while also determining the coefficients for each.

- Name: ext_euclid
  Prefix: cpp
  Display: Extended Euclidean Algorithm
  Description: Calculates the GCD of A and B while also determining the coefficients for each.

- Name: inv_modulo
  Prefix: cpp
  Display: Inverse Modulo
  Description: Returns the modular inverse of a given value using the extended euclidean algorithm.
  Dependencies: [ext_euclid]

- Name: sieve_erato
  Prefix: cpp
  Display: Sieve of Eratosthenes
  Description: Find all prime numbers less than or equal to N.

- Name: template
  Prefix: cpp
  Display: C++ Template
  Description: A general C++ solution template.
